### ISSUE TITLE
Optifine Broken

### ISSUE THREAD

**Issue by UltraBlackLinux** [UltraBlackLinux/MultiMC-Patch-Gen#1]
Doesn't work atm. Need help of my community:

java.lang.ClassNotFoundException: optifine.OptiFineTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by UltraBlackLinux** [comment]
BTW where the heck should i put the optifine.jar xD

**Comment by UltraBlackLinux** [comment]
everything works now :D
